name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        working-directory: ./pawsReactApp
        run: npm ci
      - name: Lint
        working-directory: ./pawsReactApp
        run: npm run lint