name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        working-directory: ./pawsReactApp
        run: npm ci
      - name: Unit Test
        working-directory: ./pawsReactApp
        run: npm run test